### ISSUE TITLE
basic sqlalchemy support for pg13

### ISSUE THREAD

**Issue by abe-winter** [abe-winter/pg13-py#5]
support pg13 as a backend for sqlalchemy. I think this will seriously increase the usability of the tool for people.

**Comment by kristi** [comment]
+1 It would also be nice if pg13 supported a more familiar dbapi2 interface https://www.python.org/dev/peps/pep-0249/
That would likely make creating a sqlalchemy dialect easier.
Cool project though, hope you keep developing this :)

**Comment by abe-winter** [comment]
@kristi agreed -- I'm opening your suggestion as #12 and prioritizing it for the next incremental release

**Comment by abe-winter** [comment]
SQLA support is limited but basic things work (create table, insert, select) and the skeleton is there for future work.
